import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';
import {
  Plus,
  FileText,
  Upload,
  Calendar,
  MapPin,
  User,
  CheckCircle,
  Clock,
  XCircle,
  Search,
  Download,
  Eye,
  File,
  Building,
  Map,
  Shield,
  Check
} from 'lucide-react';
import { Claim, NewClaimSubmission } from '../../types';
import { claimsAPI } from '../../utils/api';
import LoadingSpinner from '../../components/UI/LoadingSpinner';

const Claims: React.FC = () => {
  const { t } = useTranslation();
  const [claims, setClaims] = useState<Claim[]>([]);
  const [pendingClaims, setPendingClaims] = useState<Claim[]>([]);
  const [loading, setLoading] = useState(false);
  const [showNewClaimForm, setShowNewClaimForm] = useState(false);
  const [selectedClaim, setSelectedClaim] = useState<Claim | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'Pending' | 'Approved' | 'Rejected'>('all');
  const [activeTab, setActiveTab] = useState<'all' | 'pending'>('all');
  
  // Form state
  const [formData, setFormData] = useState<Partial<NewClaimSubmission>>({
    personal_info: {
      first_name: '',
      last_name: '',
      gender: '',
      tribal_community: '',
      aadhaar: '',
      income: 0
    },
    title_info: {
      right_type: '',
      status: 'Under_Review',
      claim_area_hectares: 0,
      polygon_coordinates: []
    },
    admin_info: {
      village_id: 'VIL_000001',
      village: '',
      gp: '',
      block: 'Mandla',
      district: 'Mandla',
      state: 'Madhya Pradesh',
      forest_area_hectares: 0,
      block_id: 'BLK_000001',
      gp_id: 'GP_000001'
    },
    asset_summary: {
      total_area_hectares: 0,
      asset_types: [],
      assets_count: 0
    },
    vulnerability: {
      score: 0,
      category: null
    },
    statuses: {
      gramasabha: 'Pending',
      sdlc: {
        review: false,
        remarks: []
      },
      dlc: null
    }
  });
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    loadClaims();
    loadPendingClaims();
  }, []);

  const loadClaims = async () => {
    setLoading(true);
    try {
      const claimsData = await claimsAPI.getAll();
      setClaims(claimsData);
    } catch (error) {
      console.error('Failed to load claims:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadPendingClaims = async () => {
    try {
      // Load pending claims from localStorage or API
      const stored = localStorage.getItem('pendingClaims');
      if (stored) {
        const pendingData = JSON.parse(stored);
        setPendingClaims(pendingData);
      }
    } catch (error) {
      console.error('Failed to load pending claims:', error);
    }
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    
    try {
      // Validate required fields
      if (!formData.personal_info?.first_name || !formData.personal_info?.last_name) {
        alert('Please fill in all required personal information fields');
        return;
      }
      
      if (!formData.title_info?.right_type || !formData.title_info?.claim_area_hectares) {
        alert('Please fill in all required title information fields');
        return;
      }
      
      if (!formData.admin_info?.village || !formData.admin_info?.gp) {
        alert('Please fill in all required administrative information fields');
        return;
      }
      
      if (!formData.asset_summary?.total_area_hectares || !formData.asset_summary?.asset_types?.length) {
        alert('Please fill in all required asset summary fields');
        return;
      }

      // Create the submission data
      const submissionData: NewClaimSubmission = {
        beneficiary_id: '', // Will be generated by API
        title_id: '', // Will be generated by API
        personal_info: formData.personal_info!,
        title_info: formData.title_info!,
        admin_info: formData.admin_info!,
        asset_summary: formData.asset_summary!,
        vulnerability: formData.vulnerability!,
        statuses: formData.statuses!
      };

      // Submit the claim
      const newClaim = await claimsAPI.submitNewClaim(submissionData);
      
      // Add to pending claims
      const updatedPendingClaims = [...pendingClaims, newClaim];
      setPendingClaims(updatedPendingClaims);
      localStorage.setItem('pendingClaims', JSON.stringify(updatedPendingClaims));
      
      // Reset form
      setFormData({
        personal_info: {
          first_name: '',
          last_name: '',
          gender: '',
          tribal_community: '',
          aadhaar: '',
          income: 0
        },
        title_info: {
          right_type: '',
          status: 'Under_Review',
          claim_area_hectares: 0,
          polygon_coordinates: []
        },
        admin_info: {
          village_id: 'VIL_000001',
          village: '',
          gp: '',
          block: 'Mandla',
          district: 'Mandla',
          state: 'Madhya Pradesh',
          forest_area_hectares: 0,
          block_id: 'BLK_000001',
          gp_id: 'GP_000001'
        },
        asset_summary: {
          total_area_hectares: 0,
          asset_types: [],
          assets_count: 0
        },
        vulnerability: {
          score: 0,
          category: null
        },
        statuses: {
          gramasabha: 'Pending',
          sdlc: {
            review: false,
            remarks: []
          },
          dlc: null
        }
      });
      setUploadedFiles([]);
      setShowNewClaimForm(false);
      
      alert('Claim submitted successfully! It will appear in the pending claims section for approval.');
    } catch (error) {
      console.error('Error submitting claim:', error);
      const errorMessage = error instanceof Error ? error.message : 'Error submitting claim. Please try again.';
      alert(errorMessage);
    } finally {
      setSubmitting(false);
    }
  };

  const handleApproveClaim = async (claimId: string) => {
    try {
      await claimsAPI.approveClaim(claimId);
      
      // Update pending claims
      const updatedPendingClaims = pendingClaims.filter(claim => claim.id !== claimId);
      setPendingClaims(updatedPendingClaims);
      localStorage.setItem('pendingClaims', JSON.stringify(updatedPendingClaims));
      
      // Add to main claims list
      const approvedClaim = pendingClaims.find(claim => claim.id === claimId);
      if (approvedClaim) {
        const updatedClaim = {
          ...approvedClaim,
          status: 'Approved' as const,
          statuses: {
            ...approvedClaim.statuses,
            gramasabha: 'Approved' as const
          }
        };
        setClaims(prevClaims => [...prevClaims, updatedClaim]);
      }
      
      alert('Claim approved successfully!');
    } catch (error) {
      console.error('Error approving claim:', error);
      const errorMessage = error instanceof Error ? error.message : 'Error approving claim. Please try again.';
      alert(errorMessage);
    }
  };

  const handleInputChange = (section: string, field: string, value: any) => {
    setFormData(prev => ({
      ...prev,
      [section]: {
        ...(prev[section as keyof typeof prev] as any),
        [field]: value
      }
    }));
  };

  const handleAssetTypeChange = (assetType: string, checked: boolean) => {
    setFormData(prev => ({
      ...prev,
      asset_summary: {
        ...prev.asset_summary!,
        asset_types: checked 
          ? [...(prev.asset_summary?.asset_types || []), assetType]
          : (prev.asset_summary?.asset_types || []).filter(type => type !== assetType)
      }
    }));
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    setUploadedFiles(prev => [...prev, ...files]);
  };

  const currentClaims = activeTab === 'all' ? claims : pendingClaims;
  
  const filteredClaims = currentClaims.filter(claim => {
    const matchesSearch = claim.applicantName.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         claim.id.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || claim.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Approved': return <CheckCircle className="w-5 h-5 text-green-600" />;
      case 'Pending': return <Clock className="w-5 h-5 text-yellow-600" />;
      case 'Rejected': return <XCircle className="w-5 h-5 text-red-600" />;
      default: return null;
    }
  };

  const getStatusBadge = (status: string) => {
    const baseClasses = "px-3 py-1 rounded-full text-xs font-medium";
    switch (status) {
      case 'Approved':
        return `${baseClasses} bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-300`;
      case 'Pending':
        return `${baseClasses} bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-300`;
      case 'Rejected':
        return `${baseClasses} bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-300`;
      default:
        return baseClasses;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
            {t('claims')}
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Manage and track forest rights claims
          </p>
        </div>

        <motion.button
          whileHover={{ scale: 1.02 }}
          onClick={() => setShowNewClaimForm(true)}
          className="flex items-center space-x-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-lg font-medium transition-colors"
        >
          <Plus className="w-5 h-5" />
          <span>{t('submit_claim')}</span>
        </motion.button>
      </div>

      {/* Tabs */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700">
        <div className="flex border-b border-gray-200 dark:border-gray-700">
          <button
            onClick={() => setActiveTab('all')}
            className={`flex-1 px-6 py-4 text-sm font-medium text-center border-b-2 transition-colors ${
              activeTab === 'all'
                ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
            }`}
          >
            All Claims ({claims.length})
          </button>
          <button
            onClick={() => setActiveTab('pending')}
            className={`flex-1 px-6 py-4 text-sm font-medium text-center border-b-2 transition-colors ${
              activeTab === 'pending'
                ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
            }`}
          >
            Pending Approval ({pendingClaims.length})
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700">
        <div className="flex flex-col lg:flex-row gap-4">
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder="Search by applicant name or claim ID"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
          </div>

          <div className="flex items-center space-x-4">
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as any)}
              className="px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="all">All Status</option>
              <option value="Pending">Pending</option>
              <option value="Approved">Approved</option>
              <option value="Rejected">Rejected</option>
            </select>

            <button className="p-3 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
              <Download className="w-5 h-5 text-gray-600 dark:text-gray-400" />
            </button>
          </div>
        </div>
      </div>

      {/* Claims Grid */}
      {loading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner size="lg" />
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
          {filteredClaims.map((claim) => (
            <motion.div
              key={claim.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              whileHover={{ scale: 1.02, y: -5 }}
              className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 cursor-pointer"
              onClick={() => setSelectedClaim(claim)}
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center space-x-3">
                  {getStatusIcon(claim.status)}
                  <div>
                    <h3 className="font-semibold text-gray-900 dark:text-white">
                      {claim.claimType} - {claim.id.slice(-6)}
                    </h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400">
                      {claim.personal_info ? `${claim.personal_info.first_name} ${claim.personal_info.last_name}` : claim.applicantName}
                    </p>
                  </div>
                </div>
                <span className={getStatusBadge(claim.status)}>
                  {claim.status}
                </span>
              </div>

              {/* Personal Information */}
              {claim.personal_info && (
                <div className="mb-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                  <div className="flex items-center space-x-2 mb-2">
                    <User className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                    <span className="text-sm font-medium text-blue-800 dark:text-blue-300">Personal Details</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs text-gray-600 dark:text-gray-400">
                    <div>Gender: {claim.personal_info.gender}</div>
                    <div>Community: {claim.personal_info.tribal_community}</div>
                    <div>Income: ₹{claim.personal_info.income.toLocaleString()}</div>
                    <div>Aadhaar: {claim.personal_info.aadhaar}</div>
                  </div>
                </div>
              )}

              {/* Administrative Information */}
              {claim.admin_info && (
                <div className="space-y-2 text-sm text-gray-600 dark:text-gray-400 mb-4">
                  <div className="flex items-center space-x-2">
                    <MapPin className="w-4 h-4" />
                    <span>{claim.admin_info.village}, {claim.admin_info.block}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Building className="w-4 h-4" />
                    <span>GP: {claim.admin_info.gp}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Map className="w-4 h-4" />
                    <span>Forest Area: {claim.admin_info.forest_area_hectares.toFixed(2)} ha</span>
                  </div>
                </div>
              )}

              {/* Title Information */}
              {claim.title_info && (
                <div className="mb-4 p-3 bg-green-50 dark:bg-green-900/20 rounded-lg">
                  <div className="flex items-center space-x-2 mb-2">
                    <FileText className="w-4 h-4 text-green-600 dark:text-green-400" />
                    <span className="text-sm font-medium text-green-800 dark:text-green-300">Title Details</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs text-gray-600 dark:text-gray-400">
                    <div>Right Type: {claim.title_info.right_type}</div>
                    <div>Area: {claim.title_info.claim_area_hectares} ha</div>
                  </div>
                </div>
              )}

              {/* Asset Summary */}
              {claim.asset_summary && (
                <div className="mb-4 p-3 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
                  <div className="flex items-center space-x-2 mb-2">
                    <Shield className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                    <span className="text-sm font-medium text-purple-800 dark:text-purple-300">Assets</span>
                  </div>
                  <div className="text-xs text-gray-600 dark:text-gray-400">
                    <div>Total Area: {claim.asset_summary.total_area_hectares} ha</div>
                    <div>Assets: {claim.asset_summary.assets_count} ({claim.asset_summary.asset_types.join(', ')})</div>
                  </div>
                </div>
              )}

              {/* Vulnerability Assessment */}
              {claim.vulnerability && (
                <div className="mb-4 p-3 bg-orange-50 dark:bg-orange-900/20 rounded-lg">
                  <div className="flex items-center space-x-2 mb-2">
                    <Shield className="w-4 h-4 text-orange-600 dark:text-orange-400" />
                    <span className="text-sm font-medium text-orange-800 dark:text-orange-300">Vulnerability</span>
                  </div>
                  <div className="text-xs text-gray-600 dark:text-gray-400">
                    <div>Score: {claim.vulnerability.score.toFixed(2)}</div>
                    {claim.vulnerability.category && <div>Category: {claim.vulnerability.category}</div>}
                  </div>
                </div>
              )}

              <div className="flex items-center space-x-2 text-sm text-gray-600 dark:text-gray-400">
                <Calendar className="w-4 h-4" />
                <span>{new Date(claim.submissionDate).toLocaleDateString()}</span>
              </div>

              <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-gray-500 dark:text-gray-400">
                    {claim.uploadedFiles?.length || claim.evidence.length} documents
                  </span>
                  <div className="flex items-center space-x-2">
                    {activeTab === 'pending' && claim.status === 'Pending' && (
                      <motion.button
                        whileHover={{ scale: 1.05 }}
                        onClick={(e) => {
                          e.stopPropagation();
                          handleApproveClaim(claim.id);
                        }}
                        className="flex items-center space-x-1 px-3 py-1 bg-green-600 hover:bg-green-700 text-white text-xs rounded-lg transition-colors"
                      >
                        <Check className="w-3 h-3" />
                        <span>Approve</span>
                      </motion.button>
                    )}
                    <div className="flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400">
                      <Eye className="w-4 h-4" />
                      <span>View Details</span>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}

      {/* New Claim Form Modal */}
      {showNewClaimForm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white dark:bg-gray-800 rounded-xl p-6 w-full max-w-5xl max-h-[95vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                {t('submit_claim')}
              </h2>
              <button
                onClick={() => setShowNewClaimForm(false)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
              >
                <XCircle className="w-6 h-6" />
              </button>
            </div>

            {/* Form Instructions */}
            <div className="mb-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
              <div className="flex items-start space-x-3">
                <div className="flex-shrink-0">
                  <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400 mt-0.5" />
                </div>
                <div>
                  <h3 className="text-sm font-medium text-blue-800 dark:text-blue-300 mb-2">
                    Form Instructions
                  </h3>
                  <ul className="text-sm text-blue-700 dark:text-blue-400 space-y-1">
                    <li>• Fill in all required fields marked with *</li>
                    <li>• Upload supporting documents (PDF, JPG, PNG, MP3, MP4)</li>
                    <li>• Ensure all personal and administrative information is accurate</li>
                    <li>• Select appropriate asset types based on your claim</li>
                    <li>• Vulnerability assessment is optional but recommended</li>
                  </ul>
                </div>
              </div>
            </div>

            <form onSubmit={handleFormSubmit} className="space-y-6">
              {/* Personal Information Section */}
              <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
                <div className="flex items-center space-x-2 mb-4">
                  <User className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                  <h3 className="text-lg font-semibold text-blue-800 dark:text-blue-300">
                    Personal Information
                  </h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      First Name *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.personal_info?.first_name || ''}
                      onChange={(e) => handleInputChange('personal_info', 'first_name', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter first name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Last Name *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.personal_info?.last_name || ''}
                      onChange={(e) => handleInputChange('personal_info', 'last_name', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter last name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Gender *
                    </label>
                    <select 
                      required 
                      value={formData.personal_info?.gender || ''}
                      onChange={(e) => handleInputChange('personal_info', 'gender', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    >
                      <option value="">Select Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Tribal Community *
                    </label>
                    <select 
                      required 
                      value={formData.personal_info?.tribal_community || ''}
                      onChange={(e) => handleInputChange('personal_info', 'tribal_community', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    >
                      <option value="">Select Tribal Community</option>
                      <option value="Baiga">Baiga</option>
                      <option value="Gond">Gond</option>
                      <option value="Kol">Kol</option>
                      <option value="Bhil">Bhil</option>
                      <option value="Sahariya">Sahariya</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Aadhaar Number *
                    </label>
                    <input
                      type="text"
                      required
                      pattern="[0-9]{4}-[0-9]{4}-[0-9]{4}"
                      value={formData.personal_info?.aadhaar || ''}
                      onChange={(e) => handleInputChange('personal_info', 'aadhaar', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="1234-5678-9012"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Annual Income (₹) *
                    </label>
                    <input
                      type="number"
                      required
                      min="0"
                      value={formData.personal_info?.income || ''}
                      onChange={(e) => handleInputChange('personal_info', 'income', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="50000"
                    />
                  </div>
                </div>
              </div>

              {/* Administrative Information Section */}
              <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-lg">
                <div className="flex items-center space-x-2 mb-4">
                  <Building className="w-5 h-5 text-green-600 dark:text-green-400" />
                  <h3 className="text-lg font-semibold text-green-800 dark:text-green-300">
                    Administrative Information
                  </h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Village *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.admin_info?.village || ''}
                      onChange={(e) => handleInputChange('admin_info', 'village', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter village name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Gram Panchayat *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.admin_info?.gp || ''}
                      onChange={(e) => handleInputChange('admin_info', 'gp', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter Gram Panchayat name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Block *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.admin_info?.block || ''}
                      onChange={(e) => handleInputChange('admin_info', 'block', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter block name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      District *
                    </label>
                    <input
                      type="text"
                      required
                      value={formData.admin_info?.district || ''}
                      onChange={(e) => handleInputChange('admin_info', 'district', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="Enter district name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      State *
                    </label>
                    <select 
                      required 
                      value={formData.admin_info?.state || ''}
                      onChange={(e) => handleInputChange('admin_info', 'state', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    >
                      <option value="">Select State</option>
                      <option value="Madhya Pradesh">Madhya Pradesh</option>
                      <option value="Chhattisgarh">Chhattisgarh</option>
                      <option value="Jharkhand">Jharkhand</option>
                      <option value="Odisha">Odisha</option>
                      <option value="Maharashtra">Maharashtra</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Forest Area (hectares) *
                    </label>
                    <input
                      type="number"
                      required
                      step="0.01"
                      min="0"
                      value={formData.admin_info?.forest_area_hectares || ''}
                      onChange={(e) => handleInputChange('admin_info', 'forest_area_hectares', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="100.00"
                    />
                  </div>
                </div>
              </div>

              {/* Title Information Section */}
              <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg">
                <div className="flex items-center space-x-2 mb-4">
                  <FileText className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                  <h3 className="text-lg font-semibold text-purple-800 dark:text-purple-300">
                    Title Information
                  </h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Right Type *
                    </label>
                    <select 
                      required 
                      value={formData.title_info?.right_type || ''}
                      onChange={(e) => handleInputChange('title_info', 'right_type', e.target.value)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    >
                      <option value="">Select Right Type</option>
                      <option value="IFR">Individual Forest Rights (IFR)</option>
                      <option value="CR">Community Rights (CR)</option>
                      <option value="CFR">Community Forest Resources (CFR)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Claim Area (hectares) *
                    </label>
                    <input
                      type="number"
                      required
                      step="0.01"
                      min="0"
                      value={formData.title_info?.claim_area_hectares || ''}
                      onChange={(e) => handleInputChange('title_info', 'claim_area_hectares', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="1.50"
                    />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      GPS Coordinates (Optional)
                    </label>
                    <textarea
                      value={JSON.stringify(formData.title_info?.polygon_coordinates || [])}
                      onChange={(e) => {
                        try {
                          const coords = JSON.parse(e.target.value);
                          handleInputChange('title_info', 'polygon_coordinates', coords);
                        } catch (error) {
                          // Invalid JSON, ignore
                        }
                      }}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      rows={3}
                      placeholder="Enter GPS coordinates or polygon coordinates (JSON format)"
                    />
                  </div>
                </div>
              </div>

              {/* Asset Summary Section */}
              <div className="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-lg">
                <div className="flex items-center space-x-2 mb-4">
                  <Shield className="w-5 h-5 text-orange-600 dark:text-orange-400" />
                  <h3 className="text-lg font-semibold text-orange-800 dark:text-orange-300">
                    Asset Summary
                  </h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Total Area (hectares) *
                    </label>
                    <input
                      type="number"
                      required
                      step="0.01"
                      min="0"
                      value={formData.asset_summary?.total_area_hectares || ''}
                      onChange={(e) => handleInputChange('asset_summary', 'total_area_hectares', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="2.00"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Number of Assets *
                    </label>
                    <input
                      type="number"
                      required
                      min="1"
                      value={formData.asset_summary?.assets_count || ''}
                      onChange={(e) => handleInputChange('asset_summary', 'assets_count', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="3"
                    />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Asset Types *
                    </label>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                      {['Water_Body', 'Forest_Patch', 'Agricultural_Land', 'Community_Forest', 'Water_Source', 'Traditional_Medicinal_Plants'].map((assetType) => (
                        <label key={assetType} className="flex items-center space-x-2">
                          <input 
                            type="checkbox" 
                            className="rounded border-gray-300"
                            checked={formData.asset_summary?.asset_types?.includes(assetType) || false}
                            onChange={(e) => handleAssetTypeChange(assetType, e.target.checked)}
                          />
                          <span className="text-sm text-gray-700 dark:text-gray-300">
                            {assetType.replace(/_/g, ' ')}
                          </span>
                        </label>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* Vulnerability Assessment Section */}
              <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
                <div className="flex items-center space-x-2 mb-4">
                  <Shield className="w-5 h-5 text-red-600 dark:text-red-400" />
                  <h3 className="text-lg font-semibold text-red-800 dark:text-red-300">
                    Vulnerability Assessment (Optional)
                  </h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Vulnerability Score (0-100)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      step="0.01"
                      value={formData.vulnerability?.score || ''}
                      onChange={(e) => handleInputChange('vulnerability', 'score', Number(e.target.value))}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                      placeholder="25.50"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Risk Category
                    </label>
                    <select 
                      value={formData.vulnerability?.category || ''}
                      onChange={(e) => handleInputChange('vulnerability', 'category', e.target.value || null)}
                      className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    >
                      <option value="">Select Risk Category</option>
                      <option value="Low Risk">Low Risk</option>
                      <option value="Medium Risk">Medium Risk</option>
                      <option value="High Risk">High Risk</option>
                    </select>
                  </div>
                </div>
              </div>

              {/* Document Upload Section */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  {t('upload_documents')} *
                </label>
                <div className="border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg p-8 text-center">
                  <Upload className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                  <p className="text-gray-600 dark:text-gray-400 mb-2">
                    Drop files here or click to upload supporting documents
                  </p>
                  <p className="text-sm text-gray-500 dark:text-gray-500 mb-4">
                    Supports: PDF, JPG, PNG, MP3, MP4 (max 10MB each)
                  </p>
                  <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">
                    Required documents: Land deed, Identity proof, Community consent (if applicable)
                  </p>
                  <input
                    type="file"
                    multiple
                    accept=".pdf,.jpg,.jpeg,.png,.mp3,.mp4,.wav"
                    className="hidden"
                    id="file-upload"
                    onChange={handleFileUpload}
                  />
                  <label
                    htmlFor="file-upload"
                    className="mt-4 inline-flex items-center px-6 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg cursor-pointer transition-colors"
                  >
                    <Upload className="w-4 h-4 mr-2" />
                    Choose Files
                  </label>
                  
                  {/* Display uploaded files */}
                  {uploadedFiles.length > 0 && (
                    <div className="mt-4">
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Uploaded Files:</h4>
                      <div className="space-y-2">
                        {uploadedFiles.map((file, index) => (
                          <div key={index} className="flex items-center justify-between p-2 bg-gray-100 dark:bg-gray-700 rounded-lg">
                            <span className="text-sm text-gray-700 dark:text-gray-300">{file.name}</span>
                            <button
                              type="button"
                              onClick={() => setUploadedFiles(prev => prev.filter((_, i) => i !== index))}
                              className="text-red-500 hover:text-red-700"
                            >
                              <XCircle className="w-4 h-4" />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              <div className="flex items-center justify-end space-x-4 pt-6 border-t border-gray-200 dark:border-gray-700">
                <button
                  type="button"
                  onClick={() => setShowNewClaimForm(false)}
                  className="px-6 py-3 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                >
                  {t('cancel')}
                </button>
                <motion.button
                  whileHover={{ scale: submitting ? 1 : 1.02 }}
                  type="submit"
                  disabled={submitting}
                  className={`px-6 py-3 rounded-lg transition-colors flex items-center space-x-2 ${
                    submitting 
                      ? 'bg-gray-400 cursor-not-allowed text-white' 
                      : 'bg-emerald-600 hover:bg-emerald-700 text-white'
                  }`}
                >
                  {submitting && <LoadingSpinner size="sm" />}
                  <span>{submitting ? 'Submitting...' : t('submit')}</span>
                </motion.button>
              </div>
            </form>
          </motion.div>
        </div>
      )}

      {/* Claim Detail Modal */}
      {selectedClaim && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white dark:bg-gray-800 rounded-xl p-6 w-full max-w-4xl max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                Claim Details - {selectedClaim.id}
              </h2>
              <button
                onClick={() => setSelectedClaim(null)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
              >
                <XCircle className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-6">
              {/* Status and Basic Info */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="md:col-span-2">
                  <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Status
                  </h3>
                  <span className={getStatusBadge(selectedClaim.status)}>
                    {selectedClaim.status}
                  </span>
                </div>
                <div>
                  <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Submission Date
                  </h3>
                  <p className="text-gray-900 dark:text-white">
                    {new Date(selectedClaim.submissionDate).toLocaleDateString()}
                  </p>
                </div>
              </div>

              {/* Personal Information */}
              {selectedClaim.personal_info && (
                <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <User className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    <h3 className="text-lg font-semibold text-blue-800 dark:text-blue-300">
                      Personal Information
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Full Name</h4>
                      <p className="text-gray-900 dark:text-white">
                        {selectedClaim.personal_info.first_name} {selectedClaim.personal_info.last_name}
                      </p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Gender</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.personal_info.gender}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Tribal Community</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.personal_info.tribal_community}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Aadhaar Number</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.personal_info.aadhaar}</p>
                    </div>
                    <div className="md:col-span-2">
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Annual Income</h4>
                      <p className="text-gray-900 dark:text-white">₹{selectedClaim.personal_info.income.toLocaleString()}</p>
                    </div>
                  </div>
                </div>
              )}

              {/* Administrative Information */}
              {selectedClaim.admin_info && (
                <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <Building className="w-5 h-5 text-green-600 dark:text-green-400" />
                    <h3 className="text-lg font-semibold text-green-800 dark:text-green-300">
                      Administrative Information
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Village</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.village}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Gram Panchayat</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.gp}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Block</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.block}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">District</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.district}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">State</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.state}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Forest Area</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.admin_info.forest_area_hectares.toFixed(2)} hectares</p>
                    </div>
                  </div>
                </div>
              )}

              {/* Title Information */}
              {selectedClaim.title_info && (
                <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <FileText className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                    <h3 className="text-lg font-semibold text-purple-800 dark:text-purple-300">
                      Title Information
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Right Type</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.title_info.right_type}</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Claim Area</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.title_info.claim_area_hectares} hectares</p>
                    </div>
                    <div className="md:col-span-2">
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Title Status</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.title_info.status}</p>
                    </div>
                  </div>
                </div>
              )}

              {/* Asset Summary */}
              {selectedClaim.asset_summary && (
                <div className="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <Shield className="w-5 h-5 text-orange-600 dark:text-orange-400" />
                    <h3 className="text-lg font-semibold text-orange-800 dark:text-orange-300">
                      Asset Summary
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Total Area</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.asset_summary.total_area_hectares} hectares</p>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Assets Count</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.asset_summary.assets_count}</p>
                    </div>
                    <div className="md:col-span-2">
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Asset Types</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.asset_summary.asset_types.join(', ')}</p>
                    </div>
                  </div>
                </div>
              )}

              {/* Vulnerability Assessment */}
              {selectedClaim.vulnerability && (
                <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <Shield className="w-5 h-5 text-red-600 dark:text-red-400" />
                    <h3 className="text-lg font-semibold text-red-800 dark:text-red-300">
                      Vulnerability Assessment
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Vulnerability Score</h4>
                      <p className="text-gray-900 dark:text-white">{selectedClaim.vulnerability.score.toFixed(2)}</p>
                    </div>
                    {selectedClaim.vulnerability.category && (
                      <div>
                        <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Category</h4>
                        <p className="text-gray-900 dark:text-white">{selectedClaim.vulnerability.category}</p>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Uploaded Files */}
              {(selectedClaim.uploadedFiles && selectedClaim.uploadedFiles.length > 0) && (
                <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <File className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-300">
                      Uploaded Documents
                    </h3>
                  </div>
                  <div className="space-y-2">
                    {selectedClaim.uploadedFiles.map((file) => (
                      <div key={file.id} className="flex items-center justify-between p-3 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-600">
                        <div className="flex items-center space-x-3">
                          <FileText className="w-5 h-5 text-gray-500" />
                          <div>
                            <p className="text-sm font-medium text-gray-900 dark:text-white">{file.name}</p>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                              {file.type} • {(file.size / 1024).toFixed(1)} KB
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center space-x-2">
                          <button className="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                            <Eye className="w-4 h-4" />
                          </button>
                          <button className="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                            <Download className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Evidence Files (Legacy) */}
              {selectedClaim.evidence && selectedClaim.evidence.length > 0 && (
                <div className="bg-gray-50 dark:bg-gray-700 p-4 rounded-lg">
                  <div className="flex items-center space-x-2 mb-3">
                    <File className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-300">
                      Evidence Documents
                    </h3>
                  </div>
                  <div className="space-y-2">
                    {selectedClaim.evidence.map((file, index) => (
                      <div key={index} className="flex items-center justify-between p-3 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-600">
                        <div className="flex items-center space-x-3">
                          <FileText className="w-5 h-5 text-gray-500" />
                          <div>
                            <p className="text-sm font-medium text-gray-900 dark:text-white">{file}</p>
                          </div>
                        </div>
                        <div className="flex items-center space-x-2">
                          <button className="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                            <Eye className="w-4 h-4" />
                          </button>
                          <button className="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                            <Download className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Rejection Reason */}
              {selectedClaim.rejectionReason && (
                <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg border border-red-200 dark:border-red-800">
                  <h3 className="text-lg font-semibold text-red-800 dark:text-red-300 mb-2">
                    Rejection Reason
                  </h3>
                  <p className="text-red-700 dark:text-red-400">
                    {selectedClaim.rejectionReason}
                  </p>
                </div>
              )}
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
};

export default Claims;